---
title: "A4 BrainAge"
author: "Jorge Garcia Condado"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
knit: (
  function(inputFile, encoding) { 
    rmarkdown::render('A4BrainAge.Rmd',
      output_file = paste('results/A4BrainAge', '.html', sep=''))
      })
---

```{r, include = FALSE, warning = FALSE, message = FALSE}
library(ggplot2); library(ggpubr); library(dplyr); library(sjPlot)


knitr::opts_chunk$set(echo = FALSE, message = FALSE)
theme_set(theme_bw())
```

# BrainAge modelling in A4/Elearn study

```{r, include = FALSE}
# Load data
delta_A4 <- read.csv('~/Documents/Projects/geneticsbrainage/analysis/structural_brainage/ageml/model_age/predicted_age_sex.csv')

# Cognition biomarkers
cog_A4 <- read.csv('~/Documents/Projects/geneticsbrainage/data/ageml/factors/cognition.csv')
data_A4 <- merge(delta_A4, cog_A4, by = 'BID', all.x = TRUE)

# Blood biomarkers
ptau_A4 <- read.csv('~/Documents/Projects/geneticsbrainage/data/ageml/factors/ptau217.csv')
roche_A4 <- read.csv('~/Documents/Projects/geneticsbrainage/data/ageml/factors/roche.csv')
data_A4 <- merge(data_A4, ptau_A4, by = 'BID', all.x = TRUE)
data_A4 <- merge(data_A4, roche_A4, by = 'BID', all.x = TRUE)

# Amyloid status
status <- read.csv('~/Documents/Projects/geneticsbrainage/data/A4/status.csv')
status$Amyloid <- ifelse(status$Amyloid == 1, 'positive', 'negative')
status$e4 <- ifelse(status$e4 == 1, 'carrier', 'non-carrier')
data_A4 <- merge(data_A4, status, by = 'BID', all.x = TRUE)

# PET biomarkers
pet_tau <- read.csv('~/Documents/Projects/geneticsbrainage/data/A4/tau_features.csv')
pet_amyloid <- read.csv('~/Documents/Projects/geneticsbrainage/data/ageml/factors/pet_amyloid.csv')
data_A4 <- merge(data_A4, pet_tau, by = 'BID', all.x = TRUE)
data_A4 <- merge(data_A4, pet_amyloid, by = 'BID', all.x = TRUE)

# Demographics
demographics <- read.csv('~/Documents/Projects/geneticsbrainage/data/SUBJINFO.csv')
demographics <- demographics %>%
  rename(YearsEd = EDCCNTU)
data_A4 <- merge(data_A4, demographics, by = 'BID', all.x = TRUE)

```

``` {r}
regression_analysis <- function(data, x, y, covars) {
  
  # Filter nan values
  data <- data[complete.cases(data[, c(x, y, covars)]), ]
  
  # Scatter plot with correlation
  scatter_plot <- ggplot(data, aes(x = !!sym(y), y = !!sym(x))) +
    geom_point() +
    geom_smooth(method = 'lm', formula = y ~ x) +
    stat_cor(method = 'pearson') +
    labs(title = paste(x, "vs", y),
         x = y,
         y = x)
    
  # Create a formula for the regression model
  covar_formula <- paste(covars, collapse = " + ")
  full_formula <- as.formula(paste(x, "~", y, "+", covar_formula))
  
  # Linear regression model
  ols_results <- lm(full_formula, data = data)
  
  # Model summary
  model_summary <- summary(ols_results)
  
  # Plot model
  pred_plot <- plot_model(ols_results, type = c('pred'), terms = c(y), show.values = TRUE)
  
  # Return a list with all results
  return(list(
    scatter_plot = scatter_plot,
    regression_model = ols_results,
    model_summary = model_summary,
    predicted_values_plot = pred_plot
  ))
}
```

## Delta differences {.tabset}

### E4 status
```{r}
ggplot(subset(data_A4, !is.na(e4)), aes(x = e4, y = delta_all)) +
  geom_boxplot() +
  stat_compare_means(method = 't.test') +
  labs(title = 'Delta differences by E4 status',
       x = 'E4 status',
       y = 'Delta')
```

### Amyloid status
```{r}
ggplot(subset(data_A4, !is.na(Amyloid)), aes(x = Amyloid, y = delta_all)) +
  geom_boxplot() +
  stat_compare_means(method = 't.test') +
  labs(title = 'Delta differences by Amyloid status',
       x = 'Amyloid status',
       y = 'Delta')
```

## Cognition {.tabset}

### PACC

```{r}
regression_analysis(data_A4, 'PACC', 'delta_all', c('SEX', 'YearsEd', 'e4', 'Amyloid'))
```

### FCTOTAL96

```{r}
regression_analysis(data_A4, 'FCTOTAL96' , 'delta_all', c('SEX', 'YearsEd', 'e4', 'Amyloid'))
```

### MMSE

```{r}
regression_analysis(data_A4, 'MMSCORE', 'delta_all', c('SEX', 'YearsEd', 'e4', 'Amyloid'))
```

### Digit

```{r}
regression_analysis(data_A4, 'DIGITTOTAL', 'delta_all', c('SEX', 'YearsEd', 'e4', 'Amyloid'))
```

### LDL

```{r}
regression_analysis(data_A4, 'LDELTOTAL', 'delta_all', c('SEX', 'YearsEd', 'e4', 'Amyloid'))
```


## Blood Biomarkers {.tabset}

### pTau217

```{r}
ggplot(data_A4, aes(x = pTau217, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'pTau217 vs Delta',
       x = 'pTau217',
       y = 'Delta')

ols_results <- lm(pTau217 ~ delta_all + SEX + YearsEd + e4, data = data_A4)
summary(ols_results)
plot_model(ols_results, type = c('pred'), terms = c('delta_all'), show.values = TRUE)

ols_results <- lm(pTau217 ~ delta_all + TPP181 + NF.L + GFAP + AB42.AB40, data = data_A4)
summary(ols_results)
plot_model(ols_results, type = c('pred'), terms = c('delta_all'), show.values = TRUE)

regression_analysis(data_A4, 'pTau217', 'delta_all', c('NF.L', 'AB42.AB40', 'GFAP'))
```

### tpp181

```{r}
ggplot(data_A4, aes(x = TPP181, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'tpp181 vs Delta',
       x = 'tpp181',
       y = 'Delta')
```

### NFL

```{r}
ggplot(data_A4, aes(x = NF.L, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'NFL vs Delta',
       x = 'NFL',
       y = 'Delta')
```

### GFAP

```{r}
ggplot(data_A4, aes(x = GFAP, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'GFAP vs Delta',
       x = 'GFAP',
       y = 'Delta')
```

### AB42/40

```{r}
ggplot(data_A4, aes(x = AB42.AB40, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'AB42/40 vs Delta',
       x = 'AB42/40',
       y = 'Delta')
```

## PET Amyloid

### Composite

```{r}
ggplot(data_A4, aes(x = Composite_Summary, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'Composite vs Delta',
       x = 'Composite',
       y = 'Delta')
```

## PET Tau {.tabset}

### Inferior temporal
```{r}
# plot corelation between delta and pet tau
ggplot(data_A4, aes(x = bi_inferiortemporal, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'Inferior Temporal vs Delta',
       x = 'Inferior Temporal',
       y = 'Delta')
```

### Inferior parietal
```{r}
# plot corelation between delta and pet tau
ggplot(data_A4, aes(x = bi_inferiorparietal, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'Inferior Parietal vs Delta',
       x = 'Inferior Parietal',
       y = 'Delta')
```

### Middle temporal
```{r}
# plot corelation between delta and pet tau
ggplot(data_A4, aes(x = bi_middletemporal, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'Middle Temporal vs Delta',
       x = 'Middle Temporal',
       y = 'Delta')
```

### Entorhinal
```{r}
# plot corelation between delta and pet tau
ggplot(data_A4, aes(x = bi_entorhinal, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'Entorhinal vs Delta',
       x = 'Entorhinal',
       y = 'Delta')
```

### Parahippocampal
```{r}
# plot corelation between delta and pet tau
ggplot(data_A4, aes(x = bi_parahippocampal, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'Parahippocampal vs Delta',
       x = 'Parahippocampal',
       y = 'Delta')
```

### Fusiform

```{r}
# plot corelation between delta and pet tau
ggplot(data_A4, aes(x = bi_fusiform, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'Fusiform vs Delta',
       x = 'Fusiform',
       y = 'Delta')
```

### Amygdala

```{r}
# plot corelation between delta and pet tau
ggplot(data_A4, aes(x = bi_Amygdala, y = delta_all)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  stat_cor(method = 'pearson') +
  labs(title = 'Amygdala vs Delta',
       x = 'Amygdala',
       y = 'Delta')
```



