---
title: "HABSPETBrainAge"
author: "Jorge Garcia Condado"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
knit: (
  function(inputFile, encoding) { 
    rmarkdown::render('HABSPETBrainAge.Rmd',
      output_file = paste('../../results/HABSPETBrainAge', '.html', sep=''))
      })
---

```{r, include = FALSE, warning = FALSE, message = FALSE}
library(ggplot2); library(ggpubr); library(dplyr); library(sjPlot)


knitr::opts_chunk$set(echo = FALSE, message = FALSE)
theme_set(theme_bw())
```

# BrainAge modelling in HABS

```{r, include = FALSE}
# Load deltas
deltas <- read.csv('~/Documents/Projects/AgingBrainStudy/analysis/habs_pet_brainage/ageml/model_age/predicted_age.csv')
deltas <- deltas %>% 
  rename(delta = delta_all, predicted_age = predicted_age_all)

# Obtain deltas trained with A4
deltas_trained_wA4 <- read.csv('~/Documents/Projects/AgingBrainStudy/analysis/habs_pet_brainage_wA4/ageml/model_age/predicted_age.csv')
deltas_trained_wA4 <- deltas_trained_wA4[deltas_trained_wA4$SubjIDshort %in% grep('_', deltas_trained_wA4$SubjIDshort, value = TRUE),]
deltas_trained_wA4 <- deltas_trained_wA4 %>% 
  rename(predicted_age_trained_wA4 = predicted_age_all, delta_wA4 = delta_all) %>%
  select(SubjIDshort, predicted_age_trained_wA4, delta_wA4)
data <- merge(deltas, deltas_trained_wA4, by = 'SubjIDshort', all = TRUE)
```

## Comparison of BrainAge models


```{r}
# Plot deltas vs deltas_trained_wA4
ggplot(data = data, aes(x = delta, y = delta_wA4)) +
  geom_point() +
  stat_cor() +
  labs(x = 'Delta', y = 'Delta A4 trained', title = 'Comparison of BrainAge models')

# histogram of deltas coloured by model
ggplot(data = data, aes(x = delta, fill = 'delta')) +
  geom_histogram(alpha = 0.5, position = 'identity') +
  geom_histogram(data = data, aes(x = delta_wA4, fill = 'delta_wA4'), alpha = 0.5, position = 'identity') +
  labs(x = 'Delta', y = 'Count', title = 'Histogram of deltas coloured by model') +
  scale_fill_manual(values = c('blue', 'red'))
```

```{r}
# Caculate mean absolute error for each model
mae <- data %>% 
  summarise(mae = mean(abs(age- predicted_age)),
            mae_trained_wA4 = mean(abs(age - predicted_age_trained_wA4), na.rm = TRUE))
mae
std <- data %>% 
  summarise(std = sd(delta),
            std_trained_wA4 = sd(delta_wA4, na.rm = TRUE))
std
```